services:
  backend:
    build: ./Backend
    container_name: axis-backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./Frontend
    container_name: axis-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
